name: changed_files

on:
  push:
    branches:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: changed_files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v24

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: files.log
